services:
    mockserver:
        image: mockserver/mockserver
        container_name: mockserver
        ports:
            - 1080:1080
        volumes:
          - ./netbox_gcore_plugin/tests/mockserver/config:/config
        environment:
            - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
        networks:
            - netbox-gcore-plugin
networks:
    netbox-gcore-plugin:
